version: '3.4'

services:
  am.services.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  am.project:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

